@siteId=5
POST https://localhost:7228/tests/sites/{{siteId}}/customers
Content-Type: application/json

{
    "Id": "1",
    "SiteId": "{{siteId}}",
    "PhoneNumber": "0505727347",
    "DateOfBirth": "1999-04-08",
    "FirstName": "John",
    "LastName": "Connor"
}
